---
- name: Transfer and execute a script.
  hosts: localhost 
  tasks:

     - name: Copy and Execute the script
       command: whoami
       command: pip install docker


- hosts: localhost
  tasks:
    - docker_container:
        name: example-play
        image: python:alpine
        command: ["sleep", "1d"]

- name: Example play
  hosts: example-play
  roles:
    - name: "docker-role"

